name: Build and Test on Push

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build and Test on windows-latest
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Frends.Community.Netum.sln
    
    - name: Build solution
      run: dotnet build Frends.Community.Netum.sln --configuration Release --no-restore
    
    - name: Test solution
      run: dotnet test Frends.Community.Netum.sln --configuration Release --no-build --verbosity normal
      
    - name: Pack PdfMerge for testing
      run: dotnet pack Frends.Community.PdfMerge\Frends.Community.PdfMerge.csproj --configuration Release --include-source
      
    - name: Pack PdfSplitter for testing
      run: dotnet pack Frends.Community.PdfSplitter\Frends.Community.PdfSplitter.csproj --configuration Release --include-source