name: Pack and Push After Merge

on:
  push:
    branches:    
      - master

jobs:
  build:
    name: Release PDF Tasks
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Frends.Community.Netum.sln
    
    - name: Build solution
      run: dotnet build Frends.Community.Netum.sln --configuration Release --no-restore
    
    - name: Get PdfMerge version
      id: merge_version
      shell: pwsh
      run: |
        $version = ([xml](Get-Content -Path 'Frends.Community.PdfMerge/Frends.Community.PdfMerge.csproj')).SelectSingleNode('Project/PropertyGroup/Version').InnerText
        echo "version_number=$version" >> $env:GITHUB_OUTPUT
        
    - name: Get PdfSplitter version
      id: splitter_version
      shell: pwsh
      run: |
        $version = ([xml](Get-Content -Path 'Frends.Community.PdfSplitter/Frends.Community.PdfSplitter.csproj')).SelectSingleNode('Project/PropertyGroup/Version').InnerText
        echo "version_number=$version" >> $env:GITHUB_OUTPUT

    - name: Pack PdfMerge
      run: dotnet pack Frends.Community.PdfMerge\Frends.Community.PdfMerge.csproj --configuration Release --include-source --no-build
      
    - name: Pack PdfSplitter
      run: dotnet pack Frends.Community.PdfSplitter\Frends.Community.PdfSplitter.csproj --configuration Release --include-source --no-build
      
    - name: Push PdfMerge NuGet package
      run: dotnet nuget push Frends.Community.PdfMerge\bin\Release\Frends.Community.PdfMerge.*.nupkg --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community/api/v2/package
      if: ${{ secrets.COMMUNITY_FEED_API_KEY != '' }}
      
    - name: Push PdfSplitter NuGet package
      run: dotnet nuget push Frends.Community.PdfSplitter\bin\Release\Frends.Community.PdfSplitter.*.nupkg --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community/api/v2/package
      if: ${{ secrets.COMMUNITY_FEED_API_KEY != '' }}
    
    - name: Create Release for PdfMerge
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: PdfMerge-v${{ steps.merge_version.outputs.version_number }}
        release_name: Frends.Community.PdfMerge v${{ steps.merge_version.outputs.version_number }}
        body: |
          ## Frends.Community.PdfMerge v${{ steps.merge_version.outputs.version_number }}
          
          You can install the task via Frends UI Task View or from the NuGet package at:
          https://www.myget.org/F/frends-community/api/v2/package/Frends.Community.PdfMerge/${{ steps.merge_version.outputs.version_number }}
        draft: false
        prerelease: false
        
    - name: Create Release for PdfSplitter
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: PdfSplitter-v${{ steps.splitter_version.outputs.version_number }}
        release_name: Frends.Community.PdfSplitter v${{ steps.splitter_version.outputs.version_number }}
        body: |
          ## Frends.Community.PdfSplitter v${{ steps.splitter_version.outputs.version_number }}
          
          You can install the task via Frends UI Task View or from the NuGet package at:
          https://www.myget.org/F/frends-community/api/v2/package/Frends.Community.PdfSplitter/${{ steps.splitter_version.outputs.version_number }}
        draft: false
        prerelease: false